// מאגר מנות בסיס - Macro Tracker
const BASE_FOODS = [
  { name: "עגבנייה", cal: 18, pro: 0, cat: "ירקות", unitName: "יחידה", unitWeight: 130 },
  { name: "עגבניית שרי", cal: 18, pro: 0, cat: "ירקות", unitName: "יחידה", unitWeight: 15 },
  { name: "מלפפון", cal: 15, pro: 0, cat: "ירקות", unitName: "יחידה", unitWeight: 120 },
  { name: "פלפל אדום (גמבה)", cal: 31, pro: 0, cat: "ירקות", unitName: "יחידה", unitWeight: 150 },
  { name: "פלפל צהוב / כתום", cal: 27, pro: 0, cat: "ירקות", unitName: "יחידה", unitWeight: 150 },
  { name: "גזר", cal: 41, pro: 0, cat: "ירקות", unitName: "יחידה", unitWeight: 80 },
  { name: "בצל יבש", cal: 40, pro: 0, cat: "ירקות", unitName: "יחידה", unitWeight: 110 },
  { name: "בצל ירוק", cal: 32, pro: 0, cat: "ירקות", unitName: "גבעול", unitWeight: 15 },
  { name: "שום", cal: 149, pro: 0, cat: "ירקות", unitName: "שן", unitWeight: 4 },
  { name: "חסה ערבית / אייסברג", cal: 15, pro: 0, cat: "ירקות", unitName: "עלה", unitWeight: 20 },
  { name: "כרוב לבן", cal: 25, pro: 0, cat: "ירקות" },
  { name: "כרוב סגול", cal: 31, pro: 0, cat: "ירקות" },
  { name: "תרד חי", cal: 23, pro: 0, cat: "ירקות" },
  { name: "קישוא / זוקיני", cal: 17, pro: 0, cat: "ירקות", unitName: "יחידה", unitWeight: 180 },
  { name: "חציל אפוי / קלוי", cal: 35, pro: 0, cat: "ירקות", unitName: "יחידה", unitWeight: 300 },
  { name: "ברוקולי מבושל", cal: 35, pro: 0, cat: "ירקות" },
  { name: "כרובית מבושלת / אפויה", cal: 25, pro: 0, cat: "ירקות" },
  { name: "פטריות שמפיניון", cal: 22, pro: 0, cat: "ירקות", unitName: "יחידה", unitWeight: 18 },
  { name: "פטריות פורטובלו", cal: 22, pro: 0, cat: "ירקות", unitName: "יחידה", unitWeight: 60 },
  { name: "בטטה אפויה", cal: 90, pro: 0, cat: "ירקות", unitName: "יחידה", unitWeight: 180 },
  { name: "תפוח אדמה מבושל", cal: 87, pro: 0, cat: "ירקות", unitName: "יחידה", unitWeight: 170 },
  { name: "דלעת מבושלת / אפויה", cal: 26, pro: 0, cat: "ירקות" },
  { name: "סלק מבושל", cal: 44, pro: 0, cat: "ירקות", unitName: "יחידה", unitWeight: 120 },
  { name: "שעועית ירוקה עדינה מבושלת", cal: 31, pro: 0, cat: "ירקות" },
  { name: "מנגו", cal: 60, pro: 0, cat: "פירות", unitName: "יחידה", unitWeight: 200 },
  { name: "בננה", cal: 89, pro: 0, cat: "פירות", unitName: "יחידה", unitWeight: 110 },
  { name: "תפוח עץ", cal: 52, pro: 0, cat: "פירות", unitName: "יחידה", unitWeight: 160 },
  { name: "אגס", cal: 57, pro: 0, cat: "פירות", unitName: "יחידה", unitWeight: 160 },
  { name: "תות שדה", cal: 32, pro: 0, cat: "פירות", unitName: "יחידה", unitWeight: 15 },
  { name: "אוכמניות טריות / קפואות", cal: 57, pro: 0, cat: "פירות" },
  { name: "אבטיח", cal: 30, pro: 0, cat: "פירות", unitName: "משולש בינוני", unitWeight: 280 },
  { name: "מלון", cal: 34, pro: 0, cat: "פירות" },
  { name: "ענבים", cal: 69, pro: 0, cat: "פירות", unitName: "יחידה", unitWeight: 5 },
  { name: "תפוז", cal: 47, pro: 0, cat: "פירות", unitName: "יחידה", unitWeight: 130 },
  { name: "קלמנטינה", cal: 47, pro: 0, cat: "פירות", unitName: "יחידה", unitWeight: 85 },
  { name: "אפרסק / נקטרינה", cal: 44, pro: 0, cat: "פירות", unitName: "יחידה", unitWeight: 140 },
  { name: "קיווי", cal: 61, pro: 0, cat: "פירות", unitName: "יחידה", unitWeight: 75 },
  { name: "תמר מג'הול", cal: 277, pro: 0, cat: "פירות", unitName: "יחידה", unitWeight: 20 },
  { name: "צימוקים", cal: 299, pro: 0, cat: "פירות", unitName: "כף", unitWeight: 12 },
  { name: "טופו קשה", cal: 144, pro: 15.5, cat: "חלבונים מובחרים" },
  { name: "טופו משי", cal: 55, pro: 5.0, cat: "חלבונים מובחרים" },
  { name: "טמפה", cal: 192, pro: 20.3, cat: "חלבונים מובחרים" },
  { name: "סייטן", cal: 140, pro: 24.0, cat: "חלבונים מובחרים" },
  { name: "שבבי סויה יבשים (TVP)", cal: 330, pro: 50.0, cat: "חלבונים מובחרים" },
  { name: "יובה (עור טופו יבש)", cal: 420, pro: 52.0, cat: "חלבונים מובחרים" },
  { name: "אדממה (פולי סויה מבושלים)", cal: 122, pro: 11.0, cat: "חלבונים מובחרים" },
  { name: "אבקת חלבון צמחית", cal: 400, pro: 80.0, cat: "חלבונים מובחרים", unitName: "סקופ", unitWeight: 30 },
  { name: "שמרי בירה (פתיתים)", cal: 360, pro: 48.0, cat: "חלבונים מובחרים", unitName: "כף", unitWeight: 8 },
  { name: "חלב סויה ללא סוכר", cal: 35, pro: 3.3, cat: "חלבונים מובחרים", unitName: "כוס", unitWeight: 200 },
  { name: "יוגורט סויה טבעי", cal: 50, pro: 4.0, cat: "חלבונים מובחרים", unitName: "גביע", unitWeight: 150 },
  { name: "עדשים חומות / ירוקות מבושלות", cal: 116, pro: 9.0, cat: "קטניות" },
  { name: "עדשים כתומות מבושלות", cal: 112, pro: 8.5, cat: "קטניות" },
  { name: "עדשים שחורות (בלוגה) מבושלות", cal: 120, pro: 9.5, cat: "קטניות" },
  { name: "גרגרי חומוס מבושלים", cal: 164, pro: 8.9, cat: "קטניות" },
  { name: "שעועית שחורה מבושלת", cal: 132, pro: 8.9, cat: "קטניות" },
  { name: "שעועית לבנה מבושלת", cal: 139, pro: 9.7, cat: "קטניות" },
  { name: "שעועית אדומה (קידני) מבושלת", cal: 127, pro: 8.7, cat: "קטניות" },
  { name: "אפונה ירוקה מבושלת", cal: 81, pro: 5.4, cat: "קטניות" },
  { name: "פול מצרי מבושל", cal: 110, pro: 7.6, cat: "קטניות" },
  { name: "תורמוס מבושל", cal: 119, pro: 15.6, cat: "קטניות" },
  { name: "שיבולת שועל (קוואקר יבש)", cal: 389, pro: 16.9, cat: "דגנים ופחמימות", unitName: "כף מלאה", unitWeight: 12 },
  { name: "אורז לבן מבושל", cal: 130, pro: 2.7, cat: "דגנים ופחמימות" },
  { name: "אורז מלא מבושל", cal: 112, pro: 2.6, cat: "דגנים ופחמימות" },
  { name: "פסטה רגילה מבושלת", cal: 158, pro: 5.8, cat: "דגנים ופחמימות" },
  { name: "פסטה מקמח מלא מבושלת", cal: 145, pro: 6.0, cat: "דגנים ופחמימות" },
  { name: "פסטה מקמח עדשים מבושלת", cal: 160, pro: 13.0, cat: "דגנים ופחמימות" },
  { name: "קינואה מבושלת", cal: 120, pro: 4.4, cat: "דגנים ופחמימות" },
  { name: "כוסמת מבושלת", cal: 92, pro: 3.4, cat: "דגנים ופחמימות" },
  { name: "בורגול מבושל", cal: 83, pro: 3.1, cat: "דגנים ופחמימות" },
  { name: "קוסקוס מבושל", cal: 112, pro: 3.8, cat: "דגנים ופחמימות" },
  { name: "פיתה רגילה", cal: 242, pro: 8.4, cat: "דגנים ופחמימות", unitName: "יחידה", unitWeight: 95 },
  { name: "פיתה מקמח מלא", cal: 221, pro: 9.5, cat: "דגנים ופחמימות", unitName: "יחידה", unitWeight: 95 },
  { name: "לחם אחיד", cal: 250, pro: 8.3, cat: "דגנים ופחמימות", unitName: "פרוסה", unitWeight: 30 },
  { name: "לחם מלא / מחמצת", cal: 240, pro: 10.0, cat: "דגנים ופחמימות", unitName: "פרוסה", unitWeight: 35 },
  { name: "לחם קל", cal: 180, pro: 8.0, cat: "דגנים ופחמימות", unitName: "פרוסה", unitWeight: 25 },
  { name: "טורטיה", cal: 300, pro: 7.5, cat: "דגנים ופחמימות", unitName: "יחידה בינונית", unitWeight: 40 },
  { name: "פריכיות אורז", cal: 375, pro: 7.5, cat: "דגנים ופחמימות", unitName: "יחידה", unitWeight: 8 },
  { name: "טחינה מוכנה", cal: 213, pro: 6.7, cat: "שומנים וממרחים", unitName: "כף", unitWeight: 15 },
  { name: "טחינה גולמית", cal: 595, pro: 17.0, cat: "שומנים וממרחים", unitName: "כף", unitWeight: 15 },
  { name: "חומוס ממרח מוכן", cal: 240, pro: 7.0, cat: "שומנים וממרחים", unitName: "כף", unitWeight: 25 },
  { name: "חמאת בוטנים טבעית", cal: 588, pro: 25.0, cat: "שומנים וממרחים", unitName: "כף שטוחה", unitWeight: 15 },
  { name: "שקדים טבעיים", cal: 579, pro: 21.0, cat: "שומנים וממרחים", unitName: "יחידה", unitWeight: 1.2 },
  { name: "אגוזי מלך", cal: 654, pro: 15.2, cat: "שומנים וממרחים", unitName: "חצי אגוז", unitWeight: 2.5 },
  { name: "אגוזי קשיו", cal: 553, pro: 18.0, cat: "שומנים וממרחים", unitName: "יחידה", unitWeight: 1.5 },
  { name: "גרעיני דלעת קלופים", cal: 559, pro: 30.0, cat: "שומנים וממרחים", unitName: "כף", unitWeight: 10 },
  { name: "זרעי צ'יה", cal: 486, pro: 16.5, cat: "שומנים וממרחים", unitName: "כף", unitWeight: 12 },
  { name: "זרעי פשתן טחונים", cal: 534, pro: 18.3, cat: "שומנים וממרחים", unitName: "כף", unitWeight: 10 },
  { name: "שמן זית", cal: 884, pro: 0, cat: "שומנים וממרחים", unitName: "כף", unitWeight: 10 },
  { name: "אבוקדו", cal: 160, pro: 0, cat: "שומנים וממרחים", unitName: "חצי", unitWeight: 75 },
  { name: "זיתים ירוקים / שחורים", cal: 145, pro: 0, cat: "שומנים וממרחים", unitName: "יחידה", unitWeight: 4 },
  { name: "בירה (לאגר)", cal: 42, pro: 0.5, cat: "אלכוהול", unitName: "בקבוק 330 מ\"ל", unitWeight: 330 },
  { name: "יין אדום יבש", cal: 85, pro: 0.1, cat: "אלכוהול", unitName: "כוס 150 מ\"ל", unitWeight: 150 },
  { name: "יין לבן יבש", cal: 82, pro: 0.1, cat: "אלכוהול", unitName: "כוס 150 מ\"ל", unitWeight: 150 },
  { name: "וויסקי", cal: 231, pro: 0, cat: "אלכוהול", unitName: "שוט 40 מ\"ל", unitWeight: 40 },
  { name: "ערק / וודקה (40%)", cal: 231, pro: 0, cat: "אלכוהול", unitName: "שוט 40 מ\"ל", unitWeight: 40 },
  { name: "ג'ין", cal: 231, pro: 0, cat: "אלכוהול", unitName: "שוט 40 מ\"ל", unitWeight: 40 }
];
